"""Coherent, fictional company snapshot. Never represents real CyberAnt commitments."""
from pathlib import Path
from datetime import date,timedelta
from collections import Counter
import json,csv,sqlite3,hashlib

ROOT=Path(__file__).parent
SNAPSHOT='2026-09-05'
ROLES=['sale','technical','admin']
TECH=['technical','admin']
def money(n):return f'{n:,.0f}'.replace(',','.')+' VND'
def build():
    import seed_data
    docs=[dict(d) for d in seed_data.DOCS]
    records=[]
    def doc(id,title,category,body,roles=None,customer=None,**extra):
        d=dict(id=id,title=title,category=category,body=body,roles=roles or ROLES,customer=customer,version='company-demo-2.0',status='approved',valid_from='2026-01-01',valid_to='2027-12-31',owner='Ban điều hành giả lập',synthetic=True,as_of=SNAPSHOT,**extra)
        docs.append(d);return d
    def rec(kind,id,title,fields,body,roles=None,customer=None):
        d=doc(id,title,kind,body,roles,customer,fields=fields)
        if kind=='Báo giá':d['valid_to']=fields['valid_to']
        records.append(dict(id=id,kind=kind,title=title,roles=d['roles'],customer=customer,fields=fields,source_id=id));return d
    specs=[
      ('firewall','Triển khai firewall / VPN',12000000,4,'01 site, 01 firewall, tối đa 10 VLAN và 02 tunnel VPN','firewall,tường lửa,fortigate,vpn','Khảo sát routing/VLAN; thiết kế NAT/policy; cấu hình VPN; kiểm ứng dụng và bàn giao','Thiết bị và license có sẵn; tối đa 100 policy; không HA, không đổi IP diện rộng','Backup cấu hình; sơ đồ; bảng policy; UAT Internet/VPN; hướng dẫn vận hành','Chờ mua thiết bị 5–10 ngày làm việc nếu hết kho; chưa gồm kéo cáp hoặc license'),
      ('wifi','Khảo sát và cấu hình Wi-Fi',8000000,3,'01 site, tối đa 05 AP','wifi,wi-fi,wireless,access point,ap','Khảo sát RF; thiết kế SSID/VLAN; cấu hình; đo phủ sóng; kiểm roaming','Mặt bằng tối đa 500m²; cáp và PoE sẵn có; 05 AP hoặc ít hơn','Sơ đồ AP; báo cáo vùng phủ; cấu hình; UAT roaming','Chưa gồm AP, switch PoE và kéo cáp; diện tích lớn khảo sát riêng'),
      ('backup','Backup và diễn tập restore',10000000,4,'01 hệ thống nguồn, tối đa 02TB, 01 kho backup','backup,sao lưu,phục hồi,nas,restore','Đánh giá dữ liệu; lịch backup; retention; phân quyền; restore cách ly','Kho backup đủ dung lượng; quyền nguồn sẵn có; mạng LAN ổn định','Chính sách backup; báo cáo restore; runbook RPO/RTO','RPO/RTO thực tế phải đo; không cam kết theo dung lượng đơn thuần'),
      ('waf','Triển khai WAF cơ bản',14000000,5,'01 ứng dụng web, 01 tên miền, tối đa 10 API chính','waf,fortiweb,web application firewall','Khảo sát HTTP/TLS; cấu hình reverse proxy; staging policy; tuning; bàn giao','Có DNS/TLS và test account; có đầu mối ứng dụng; không thay source code','Sơ đồ luồng; chính sách; kết quả test; danh sách ngoại lệ','Chưa gồm license, chống DDoS volumetric hoặc sửa lỗi ứng dụng'),
      ('switch','Triển khai switch và VLAN',9000000,3,'01 site, tối đa 03 switch, 10 VLAN','switch,vlan,lan,mạng nội bộ','Khảo sát uplink; VLAN/trunk; STP; quản trị; kiểm kết nối','Switch và license có sẵn; không gồm cáp mới','Topology; port map; bảng VLAN; backup cấu hình','Không gồm thay cáp quang, module SFP và đi dây'),
      ('server','Máy chủ và ảo hóa',18000000,6,'02 host, tối đa 08 máy ảo','server,máy chủ,ảo hóa,vmware,hypervisor','Kiểm phần cứng; cài hypervisor; tạo mạng lưu trữ; máy ảo mẫu; bàn giao','Phần cứng tương thích đã xác minh; license hợp lệ; storage có sẵn','Danh mục VM; cấu hình network/storage; checklist backup','Chưa gồm di chuyển cơ sở dữ liệu lớn hoặc license hệ điều hành'),
      ('endpoint','Triển khai bảo vệ endpoint',6000000,2,'Tối đa 50 máy Windows trong 01 tenant','endpoint,edr,antivirus,bitdefender','Kiểm danh sách máy; pilot agent; policy; rollout; báo cáo','Máy đáp ứng cấu hình hãng; tài khoản triển khai có quyền','Danh sách agent; policy; hướng dẫn xử lý cảnh báo','Chưa gồm license; hệ điều hành không hỗ trợ cần đánh giá riêng'),
      ('pam','Triển khai PAM khởi đầu',24000000,8,'10 quản trị viên, 20 tài sản','pam,đặc quyền,privileged','Khảo sát quyền; thiết kế vault/session; tích hợp danh tính; pilot; nghiệm thu','Có directory, MFA và danh sách tài sản; license có sẵn','Ma trận quyền; workflow; biên bản kiểm truy vết','Không nhập bí mật thật vào AI; hệ thống legacy báo phạm vi riêng'),
      ('siem','Tích hợp SIEM cơ bản',20000000,7,'10 nguồn log, 05 use case','siem,soc,log,giám sát','Khảo sát nguồn; parser; đồng bộ thời gian; use case; kiểm cảnh báo','Kho log, license và kết nối có sẵn; đầu mối ứng cứu','Sơ đồ log; danh mục use case; SOP phân loại cảnh báo','EPS/lưu trữ phải đo; không hứa phát hiện mọi tấn công'),
      ('audit','Khảo sát và thiết kế hạ tầng',7000000,3,'01 site, tối đa 20 thiết bị','khảo sát,thiết kế,hld,lld,tư vấn','Phỏng vấn; inventory; topology; đánh giá hiện trạng; đề xuất','Có đầu mối IT; được phép truy cập chỉ đọc','Báo cáo hiện trạng; HLD; roadmap ưu tiên','Không gồm pentest hay thay đổi production'),
      ('training','Đào tạo và chuyển giao vận hành',5000000,2,'02 buổi, tối đa 10 học viên','đào tạo,chuyển giao,training','Khảo sát trình độ; tài liệu lab; hướng dẫn; đánh giá cuối buổi','Môi trường lab; tài khoản giả lập; lịch học thống nhất','Slide; bài lab; checklist vận hành; đánh giá','Không bao gồm chứng chỉ hãng hoặc lệ phí thi'),
      ('migration','Di chuyển firewall có kiểm soát',22000000,7,'01 site, tối đa 150 policy và 04 VPN','migration,di chuyển,đổi firewall','Đối chiếu policy; chuyển đổi lab; chạy song song; cutover; hậu kiểm','Thiết bị hai đầu sẵn có; change window; rollback được duyệt','Mapping policy; kế hoạch cutover; UAT; cấu hình hoàn công','Chưa gồm HA liên site hoặc viết lại toàn bộ thiết kế IP')]
    services=[]
    for sid,name,price,days,scope,aliases,steps,conditions,outputs,exclude in specs:
        s=dict(id=sid,name=name,price=price,days=days,scope=scope,aliases=aliases.split(','),conditions=conditions,outputs=outputs,exclusions=exclude,delivery_min=days,delivery_max=days+2,valid_from='2026-01-01',valid_to='2027-12-31',source_id='RATE-'+sid.upper())
        services.append(s)
        doc('RATE-'+sid.upper(),name+' — giá và thời gian chuẩn','Bảng giá',f'Giá DEMO {name}: {money(price)}/gói. Khối lượng: {days} ngày công kỹ sư. Lịch thực hiện mẫu: {days}–{days+2} ngày làm việc khi đủ điều kiện, chưa tính ngày chờ. Phạm vi: {scope}. Điều kiện: {conditions}. Giá chưa VAT, thiết bị, license. Hai site cùng phạm vi nhân đôi phí/ngày công nhưng lịch phải xếp theo nguồn lực. Không phải báo giá thật. Từ khóa: {aliases}.',service_id=sid,service=s)
        doc('SCOPE-'+sid.upper(),name+' — phạm vi và bàn giao','Dịch vụ',f'Bao gồm: {steps}. Quy mô: {scope}. Bàn giao: {outputs}. Ngoại lệ: {exclude}. Để tư vấn sơ bộ có thể dùng gói chuẩn; chỉ cần hỏi thêm các mục khác với phạm vi chuẩn.',service_id=sid)
        doc('PLAN-'+sid.upper(),name+' — kế hoạch triển khai','Tiến độ',f'Kế hoạch DEMO tổng {days} ngày công, khung {days}–{days+2} ngày làm việc. Bước 1: khảo sát và khóa phạm vi. Bước 2: chuẩn bị cấu hình trong lab. Bước 3: triển khai trong khung đã duyệt. Bước 4: kiểm thử các tiêu chí: {outputs}. Bước 5: ký biên bản và theo dõi sau bàn giao. Điều kiện khởi công: {conditions}. Rủi ro lịch: {exclude}. PM xác nhận lịch sau kiểm người/thiết bị.',service_id=sid)
        doc('FAQ-'+sid.upper(),name+' — câu hỏi thường gặp','FAQ',f'Hỏi: {name} giá bao nhiêu, bao lâu? Đáp: tham khảo RATE-{sid.upper()}, giá {money(price)}, {days} ngày công cho {scope}. Hỏi: Có gì trong dịch vụ? Đáp: {steps}. Hỏi: Khách cần chuẩn bị gì? Đáp: {conditions}. Hỏi: Có bàn giao tài liệu không? Đáp: {outputs}. Hỏi: Có phát sinh không? Đáp: {exclude}; phát sinh phải có change request và chấp thuận.',service_id=sid)
        doc('RUN-'+sid.upper(),name+' — runbook kỹ sư','Runbook',f'Checklist DEMO {name}. Trước triển khai: xác minh model/firmware/license và scope {scope}; sao lưu; kiểm tài khoản dự phòng; lab và phê duyệt change. Thao tác theo thứ tự: {steps}. Xác nhận thành công bằng: {outputs}. Dừng nếu mất truy cập quản trị hoặc ứng dụng trọng yếu không đạt UAT; quay lui theo bản sao đã kiểm. Thu log có mốc giờ; che bí mật; không chạy lệnh không đúng phiên bản. Owner: trưởng nhóm kỹ thuật.',TECH,service_id=sid)
    # Policies contain complete business defaults, with no blanket refusal for factual questions.
    policies=[
    ('COMPANY','Hồ sơ công ty giả lập và cơ cấu','Công ty CyberAnt DEMO có 18 nhân viên: 1 giám đốc, 1 quản lý kinh doanh, 3 sale, 2 presales, 1 PM, 7 kỹ sư, 1 điều phối dịch vụ, 1 kế toán và 1 hành chính. Giờ hành chính thứ Hai–thứ Sáu 08:30–17:30, múi giờ Asia/Bangkok. Bộ dữ liệu là ảnh chụp mô phỏng ngày 05/09/2026, không tự cập nhật thời gian thực. Dịch vụ: network, security, server, storage, backup, vận hành và đào tạo.'),
    ('CONTACT','Kênh hỗ trợ nội bộ và escalation','Kênh giả lập: sale@cyberant.example, support@cyberant.example, pm@cyberant.example; tên miền .example không gửi thư thật. Sale hỏi presales về sizing; báo giá gửi quản lý kinh doanh; triển khai gửi PM; P1 gửi điều phối dịch vụ và kỹ sư trực. Hệ thống chỉ soạn nháp, không gửi email.'),
    ('PAYMENT','Thanh toán, đặt cọc và nghiệm thu','Điều khoản DEMO cho dịch vụ một lần: 40% tạm ứng sau duyệt đơn, 40% khi triển khai xong, 20% sau nghiệm thu trong 7 ngày. Giá catalog chưa VAT, không áp dụng thuế suất thật tự động. Thuế hiển thị riêng theo báo giá. Dịch vụ theo tháng thanh toán đầu kỳ. Không công khai giá vốn và margin.'),
    ('DISCOUNT','Chiết khấu và phê duyệt thương mại','Chính sách DEMO: sale được đề xuất 0–5%, trưởng kinh doanh duyệt tới 10%, trên 10% cần giám đốc. Mọi thay đổi giá sau duyệt phải tạo phiên bản báo giá. Đề xuất không tự trở thành phê duyệt. Phí khảo sát có thể khấu trừ theo điều khoản báo giá, không mặc định miễn phí.'),
    ('CHANGE','Phát sinh phạm vi và change request','Change request ghi nguyên nhân, đầu việc thêm/bớt, effort, giá và tác động lịch. Kỹ thuật ước lượng; PM điều phối; kinh doanh duyệt thương mại; khách xác nhận trước làm. Case phát sinh đơn giản DEMO: thêm 1 tunnel VPN vào scope đang chạy cần 0,5 ngày công, phụ phí 1.500.000 VND chưa VAT; ngoài giờ hệ số 1,5 trên phần công phát sinh, không nhân toàn hợp đồng.'),
    ('ACCEPTANCE','Tiêu chí nghiệm thu và bàn giao','Hồ sơ nghiệm thu: scope được duyệt, kết quả UAT, cấu hình backup, sơ đồ hoàn công, tài liệu vận hành, danh sách tồn đọng và người ký. Nghiệm thu một phần cần liệt kê rõ phần chưa bàn giao. Tồn đọng có owner/deadline; không chuyển dự án sang hoàn tất chỉ vì đã chạy được Internet.'),
    ('WARRANTY','Bảo hành cấu hình sau triển khai','Chính sách DEMO bảo hành lỗi cấu hình thuộc scope 30 ngày kể từ nghiệm thu. Không gồm yêu cầu mới, thay đổi do bên thứ ba, lỗi phần cứng/license/đường truyền. Trong phạm vi có thể sửa cấu hình không thu thêm phí công; kiểm bằng ticket và biên bản. Thiết bị bảo hành theo điều kiện riêng, không đồng nghĩa đổi mới ngay.'),
    ('MAINTENANCE','Quy trình bảo trì định kỳ','Bảo trì DEMO gồm kiểm CPU/RAM/storage, interface error, trạng thái HA/VPN, log bất thường, license, backup và thử restore theo lịch. Chuẩn bị 2 ngày làm việc; thông báo đầu mối; thống nhất cửa sổ. Báo cáo trong 2 ngày làm việc sau đợt bảo trì. Nâng firmware là change riêng nếu có nguy cơ gián đoạn.'),
    ('P1','Phân loại sự cố P1 P2 P3 P4','P1: dịch vụ trọng yếu ngừng toàn bộ, nhiều người ảnh hưởng và chưa có workaround. P2: suy giảm lớn hoặc site đơn lẻ ngừng nhưng có workaround. P3: lỗi không chặn hoạt động chính. P4: tư vấn hoặc yêu cầu mới. Thời gian phản hồi phụ thuộc gói BASIC/PLUS/PREMIUM; không tính từ một câu chat chưa được tạo ticket.'),
    ('RMA','RMA và thiết bị mượn mẫu','RMA DEMO: tiếp nhận hồ sơ trong 1 ngày làm việc; kiểm tra và lập yêu cầu nhà cung cấp trong 2 ngày nếu đủ serial/chứng từ. Thời gian sửa/đổi tham khảo 7–15 ngày làm việc, không bảo đảm do phụ thuộc hãng/kho. PLUS có máy mượn tùy kho và hợp đồng; PREMIUM ưu tiên giữ 1 thiết bị tương đương khi có điều khoản. Máy mượn trả trong 5 ngày sau nhận thiết bị thay thế.'),
    ('RENTAL','Cho thuê thiết bị và gia hạn','Cho thuê DEMO firewall lab: 2.500.000 VND/tháng/thiết bị, tối thiểu 3 tháng; cọc 5.000.000 VND; không gồm license bảo mật mở rộng. Phí cấu hình theo scope riêng. Kiểm bàn giao serial và cấu hình; gia hạn trước 10 ngày. Đây là hàng DEMO-GATE, không phải báo giá FortiGate thật.'),
    ('LICENSE','Quản lý license, gia hạn và EOL','Theo dõi model, serial, SKU license, thời hạn và account hãng. Nhắc gia hạn trước 60/30/7 ngày. Không suy ra tính năng từ tên thiết bị; phải đối chiếu gói license và phiên bản. EOL/EOS chỉ xác nhận theo tài liệu hãng được duyệt, không suy diễn ngày từ dữ liệu mô phỏng.'),
    ('TRAVEL','Onsite, đi lại và ngoài giờ','Điều khoản DEMO: phí công onsite theo scope; di chuyển nội thành mẫu 500.000 VND/lượt đã ghi trong báo giá; tỉnh ngoài báo thực tế trước chuyến đi. Ngoài giờ hệ số 1,5 trên công được duyệt; ngày nghỉ hệ số 2,0 nếu hợp đồng không bao gồm. Không tự nhân phụ phí vào hợp đồng cố định.'),
    ('SECURITY','Quyền dữ liệu và thông tin khách hàng','Mỗi tài khoản xem portfolio được phân công. Tài liệu kỹ thuật chi tiết chỉ kỹ thuật/admin. Báo cáo toàn công ty chỉ admin; tổng số bản ghi người dùng thấy là phạm vi của họ. Không trả dữ liệu khách khác, giá vốn, mật khẩu, private key. Dữ liệu nhập chỉ được dùng sau duyệt.'),
    ('FOLLOWUP','Cách trả lời khách và hướng dẫn sale','Trả lời trực tiếp phần đã có nguồn: lợi ích, scope, giá tham khảo, số ngày dự kiến và điều kiện. Không buộc khảo sát để giải thích khái niệm. Với câu hỏi giá chung, nêu gói chuẩn và giả định thay vì từ chối. Với cam kết cụ thể, so sánh lịch/điều kiện đã duyệt và chuyển đúng cấp. Khi được yêu cầu bảng so sánh, dùng các tiêu chí chức năng, phạm vi bảo vệ, triển khai và giới hạn.')]
    for key,title,body in policies:doc('BIZ-'+key,title,'Chính sách',body)
    comparisons=[
    ('FW-WAF','So sánh firewall mạng và WAF',[
    ['Tiêu chí','Firewall mạng','WAF'],['Mục tiêu','Kiểm soát kết nối giữa các vùng mạng','Bảo vệ ứng dụng web và API'],['Lưu lượng','Kết nối IP/port, VPN, NAT theo tính năng','HTTP/HTTPS và nội dung yêu cầu web'],['Vị trí thường dùng','Biên Internet hoặc giữa VLAN/vùng mạng','Trước web server, reverse proxy hoặc dịch vụ WAF'],['Bài toán mẫu','Chặn truy cập trái phép giữa mạng khách và máy chủ','Lọc yêu cầu web có mẫu tấn công hoặc bất thường'],['Giới hạn','Không tự thay cho bảo vệ logic ứng dụng','Không thay firewall mạng hoặc sửa source code'],['Cần phối hợp','WAF, endpoint, backup, giám sát','Firewall, phát triển ứng dụng, giám sát'],['Gói dịch vụ DEMO','12.000.000 VND / 4 ngày công','14.000.000 VND / 5 ngày công']]),
    ('BACKUP-HA','So sánh backup và HA',[
    ['Tiêu chí','Backup','HA'],['Mục đích','Khôi phục dữ liệu/trạng thái lịch sử','Duy trì dịch vụ khi một thành phần lỗi'],['Ví dụ','Sao lưu máy ảo vào kho tách biệt','Cặp thiết bị active/passive'],['Không giải quyết hết','Không chuyển đổi dịch vụ tức thì nếu chưa thiết kế','Có thể đồng bộ cả dữ liệu bị xóa/lỗi'],['Đo lường','RPO, RTO qua restore test','Thời gian chuyển đổi qua failover test'],['Kết luận','Cần kết hợp HA theo nhu cầu','Cần kết hợp backup và diễn tập']]),
    ('WARRANTY-MAINT','So sánh bảo hành và bảo trì',[
    ['Tiêu chí','Bảo hành','Bảo trì'],['Mục tiêu','Sửa lỗi thuộc trách nhiệm sản phẩm/cấu hình','Giữ hệ thống ổn định, kiểm tra định kỳ'],['Phạm vi','Theo điều kiện bảo hành và loại trừ','Theo gói và hợp đồng dịch vụ'],['Thiết bị thay thế','Tùy hãng, RMA và điều khoản','Không mặc định bao gồm phần cứng'],['Lịch','Khi có lỗi đủ điều kiện','Tháng/quý theo gói'],['Chi phí','Có thể miễn phí phần lỗi đủ điều kiện','Phí định kỳ hoặc mỗi đợt theo thỏa thuận']])]
    for key,title,rows in comparisons:
        body='\n'.join('| '+' | '.join(row)+' |' for row in rows)
        doc('CMP-'+key,title,'So sánh',body,table=rows)
    packages=[dict(id='BASIC',monthly=3000000,hours='8x5, thứ Hai–thứ Sáu 08:30–17:30',p1='4 giờ phục vụ',p2='8 giờ phục vụ',p3='2 ngày làm việc',maintenance='1 lần/quý',onsite='0 lượt bao gồm; báo riêng',loan='Không bao gồm'),dict(id='PLUS',monthly=6500000,hours='24x7',p1='1 giờ',p2='4 giờ',p3='1 ngày làm việc',maintenance='1 lần/tháng',onsite='1 lượt/quý nội thành theo lịch thống nhất',loan='Tùy kho và phụ lục'),dict(id='PREMIUM',monthly=12000000,hours='24x7',p1='30 phút',p2='2 giờ',p3='8 giờ phục vụ',maintenance='2 lần/tháng',onsite='1 lượt/tháng nội thành theo lịch thống nhất',loan='Ưu tiên 1 máy tương đương khi có phụ lục')]
    for s in packages:
        doc('SLA-'+s['id'],'Gói '+s['id']+' — bảng SLA, bảo trì và giá','SLA',f"Gói DEMO {s['id']}: {money(s['monthly'])}/tháng cho tối đa 10 thiết bị tại 1 site. Giờ hỗ trợ {s['hours']}. Phản hồi ban đầu P1: {s['p1']}; P2: {s['p2']}; P3: {s['p3']}. Đây là thời gian phản hồi, không phải thời gian khôi phục. Bảo trì: {s['maintenance']}. Onsite: {s['onsite']}. Máy mượn: {s['loan']}. Giá chưa VAT, phần cứng, license và xử lý ngoài scope. Chỉ hợp đồng cụ thể mới chốt nghĩa vụ.",package=s['id'],package_data=s)
    # Product specs are fictional lab profiles, not invented specifications of real vendor SKUs.
    products=[('GATE-100','DEMO-GATE 100','firewall',18000000,4,'8 cổng GE; profile lab văn phòng 50–100 user; không phải thông số sản phẩm hãng'),('GATE-300','DEMO-GATE 300','firewall',42000000,2,'profile lab nhiều VLAN/VPN; phải kiểm sizing theo lưu lượng'),('AP-AX','DEMO-AP AX','wifi',3200000,20,'AP Wi-Fi lab, quản lý tập trung, cấp nguồn PoE'),('SW-24','DEMO-SW 24 PoE','switch',14500000,6,'24 cổng access PoE trong mô hình giả lập'),('SW-48','DEMO-SW 48','switch',21000000,3,'48 cổng access trong mô hình giả lập'),('NAS-4','DEMO-NAS 4B','backup',22000000,3,'4 khay; giá khung chưa ổ cứng'),('HDD-8','DEMO-HDD 8TB','backup',6200000,12,'8TB theo profile giả lập; kiểm danh sách tương thích'),('SRV-1','DEMO-SERVER S1','server',78000000,1,'profile lab 16 core/128GB RAM; không đại diện model OEM'),('UPS-2','DEMO-UPS 2K','server',18000000,2,'UPS profile 2kVA; thời gian lưu điện cần đo tải'),('WAF-VM','DEMO-WAF VM','waf',35000000,5,'License thử nghiệm 1 năm cho 1 ứng dụng, dữ liệu giá giả lập'),('EDR-50','DEMO-EDR 50','endpoint',25000000,10,'Gói giả lập 50 endpoint/năm'),('PAM-20','DEMO-PAM 20','pam',65000000,2,'Gói giả lập 20 tài sản/năm'),('SIEM-10','DEMO-SIEM 10','siem',45000000,2,'Gói giả lập 10 nguồn log/năm'),('SFP-10','DEMO-SFP 10G','switch',1800000,16,'Module quang profile giả lập, kiểm tương thích thực tế'),('CAB-6','DEMO-CABLE CAT6','switch',2500000,8,'Cuộn cáp profile demo, vật tư thi công tách phí nhân công'),('LIC-GATE','DEMO-GATE SEC 1Y','firewall',9000000,6,'Gói bảo mật giả lập 1 năm; không phải bảng giá Fortinet')]
    for idx,(sku,name,sid,price,stock,desc) in enumerate(products):
        reserved=1 if stock>=2 else 0
        rec('Kho hàng','SKU-'+sku,name,dict(sku=sku,service_id=sid,price=price,on_hand=stock,reserved=reserved,available=stock-reserved,lead_days=7,unit='bộ'),f'{name}, mã {sku}: {desc}. Giá bán DEMO {money(price)}, chưa VAT. Tồn kho {stock}, đã giữ {reserved}, khả dụng {stock-reserved} bộ tại ngày {SNAPSHOT}. Nếu hết kho, lead time giả lập 7 ngày làm việc; chưa phải xác nhận giao hàng. Không sử dụng thông số demo để mua thiết bị thật.')
    names=[('A','An Minh Retail','Bán lẻ',1,60,'BASIC'),('B','Bình An Factory','Sản xuất',2,180,'PLUS'),('C','Cửu Long Logistics','Logistics',3,120,'PLUS'),('D','Đông Hải Studio','Truyền thông',1,45,'BASIC'),('E','Evergreen Office','Văn phòng',1,85,'PREMIUM'),('F','Phú Gia Foods','Thực phẩm',2,95,'PLUS'),('G','Gia Hưng Education','Đào tạo',2,150,'BASIC'),('H','Hải Đăng Clinic Lab','Phòng khám giả lập',1,70,'PREMIUM'),('I','Indigo Commerce','Thương mại',2,110,'PLUS'),('J','Kim Sơn Services','Dịch vụ',1,55,'BASIC')]
    clients=[]
    for i,(cid,name,industry,sites,users,pkg) in enumerate(names):
        client=dict(id=cid,name=name,industry=industry,sites=sites,users=users,package=pkg,owner='Minh Anh' if i%2==0 else 'Quang Duy',contact=f'it-{cid.lower()}@customer.example')
        clients.append(client)
        rec('Khách hàng','CRM-'+cid,'Hồ sơ '+name,client,f'Khách hàng hoàn toàn giả lập {name}, mã {cid}. Ngành {industry}; {sites} site; {users} user. Gói bảo trì {pkg}. Account owner {client["owner"]}. Đầu mối IT: {client["contact"]}. Xem CONTRACT-{cid}, PROJECT-{cid}-01, QUOTE-{cid}-01 và TICKET-{cid}-01. Không có thông tin cá nhân thật.',customer=cid)
        package=next(p for p in packages if p['id']==pkg)
        monthly=package['monthly']*sites
        fields=dict(customer_id=cid,package=pkg,start='2026-01-01',end='2027-12-31',sites=sites,monthly=monthly,p1=package['p1'],maintenance=package['maintenance'],status='Đang hiệu lực')
        rec('Hợp đồng','CONTRACT-'+cid,f'Hợp đồng bảo trì {name}',fields,f'Hợp đồng DEMO CONTRACT-{cid} của {name}, hiệu lực 01/01/2026–31/12/2027. Gói {pkg}, {sites} site, tối đa {10*sites} thiết bị. Phí {money(monthly)}/tháng chưa VAT. Phản hồi P1 {package["p1"]}, P2 {package["p2"]}, lịch hỗ trợ {package["hours"]}. Bảo trì {package["maintenance"]}. Onsite: {package["onsite"]}. Thời gian khôi phục theo phương án sự cố, không cam kết xử lý xong theo thời gian phản hồi. Gia hạn cần xác nhận giá mới.',customer=cid)
        for j in range(2):
            s=services[(i*2+j)%len(services)];pid=f'PROJECT-{cid}-{j+1:02}'
            status='Đã nghiệm thu' if j else 'Đã duyệt kế hoạch'
            start=date(2026,7,6)+timedelta(days=i) if j else date(2026,9,7)+timedelta(days=i%5)
            while start.weekday()>4:start+=timedelta(days=1)
            end=start
            for _ in range(s['days']*sites+1):
                end+=timedelta(days=1)
                while end.weekday()>4:end+=timedelta(days=1)
            total=s['price']*sites
            f=dict(customer_id=cid,service_id=s['id'],status=status,start=start.isoformat(),end=end.isoformat(),effort=s['days']*sites,total=total,pm='Thảo Nguyên',engineer='Hoàng Nam' if i%2 else 'Tuấn Kiệt',progress=100 if j else 0)
            rec('Dự án',pid,f'{name} — {s["name"]}',f,f'Dự án DEMO {pid}, khách {name}. Dịch vụ {s["name"]}; {sites} site, phạm vi gói chuẩn {s["scope"]}. Trạng thái {status}; tiến độ {f["progress"]}%. Lịch đã duyệt trong kịch bản {f["start"]} đến {f["end"]}; effort {f["effort"]} ngày công; phí dịch vụ {money(total)} chưa VAT. PM {f["pm"]}, kỹ sư {f["engineer"]}. Thiết bị/license và quyền truy cập đã sẵn sàng. UAT: {s["outputs"]}. Ngày trong snapshot giả lập, không phải lịch thời gian thực.',customer=cid)
            qid=f'QUOTE-{cid}-{j+1:02}'
            rec('Báo giá',qid,f'Báo giá {name} — {s["name"]}',dict(customer_id=cid,service_id=s['id'],sites=sites,subtotal=total,discount=0,status='Đã duyệt trong kịch bản',valid_to='2026-09-30',project_id=pid),f'Báo giá giả lập {qid}, khách {name}, {s["name"]}. Đơn giá {money(s["price"])} × {sites} site = {money(total)} trước VAT; chiết khấu 0%. Không gồm thiết bị và license. Thanh toán 40/40/20 theo BIZ-PAYMENT. Hiệu lực đến 30/09/2026. Quản lý kinh doanh giả lập đã duyệt; liên kết {pid}. Chỉ mô phỏng, không gửi cho khách thật.',customer=cid)
    employee_names=['Hữu Phúc','Thanh Hà','Minh Anh','Quang Duy','Ngọc Mai','Bảo Long','Khánh Linh','Thảo Nguyên','Hoàng Nam','Tuấn Kiệt','Đức Anh','Hải Yến','Trung Hiếu','Nhật Minh','Gia Bảo','Thu Hương','Lan Chi','Phương Thảo']
    jobs=['Giám đốc','Quản lý kinh doanh','Sale','Sale','Sale','Presales network','Presales security','PM','Kỹ sư network','Kỹ sư security','Kỹ sư system','Kỹ sư backup','Kỹ sư endpoint','Kỹ sư SOC','Kỹ sư triển khai','Điều phối dịch vụ','Kế toán','Hành chính']
    for i,(name,job) in enumerate(zip(employee_names,jobs)):
        slots=['08/09 sáng: có lịch','09/09 chiều: có lịch','10/09 sáng: trống'] if 5<=i<=14 else ['Liên hệ lịch qua điều phối']
        rec('Nhân sự',f'EMP-{i+1:02}',name+' — '+job,dict(name=name,job=job,email=f'employee{i+1:02}@cyberant.example',schedule=slots),f'Nhân viên giả lập {name}, vai trò {job}. Email employee{i+1:02}@cyberant.example. Lịch mẫu tuần 07–11/09/2026: {"; ".join(slots)}. Lịch trống không tự động là lịch đã đặt; PM xác nhận trước phân công. Không chứa lương hoặc dữ liệu cá nhân thật.')
    incident_types=[('VPN chập chờn','network','Sai cấu hình lifetime giữa hai đầu','Đối chiếu tham số hai đầu trong change được duyệt; theo dõi 24 giờ','TECH-VPN'),('Backup thất bại do đầy kho','backup','Retention không dọn bản cũ theo lịch','Bổ sung dung lượng, duyệt retention và chạy lại; restore mẫu thành công','TECH-RESTORE'),('Wi-Fi yếu ở phòng họp','wifi','Vị trí AP và vật cản thay đổi','Đo RF, chỉnh vị trí AP theo khảo sát, kiểm vùng phủ với cùng thiết bị','RUN-WIFI'),('WAF chặn nhầm upload','waf','Rule false positive với multipart request','Xác minh request hợp lệ, thêm ngoại lệ hẹp theo đường dẫn sau test','RUN-WAF')]
    for i,c in enumerate(clients):
        for j,(issue,area,cause,fix,ref) in enumerate(incident_types):
            tid=f'TICKET-{c["id"]}-{j+1:02}';closed=j>0;status='Đã đóng' if closed else 'Đang xử lý'
            stamp=(date(2026,9,1)+timedelta(days=j)).isoformat()
            body=f'Ticket giả lập {tid}, khách {c["name"]}. Sự cố: {issue}. Mức độ {"P2" if j==0 else "P3"}. Mở lúc {stamp} 09:00 +07; phản hồi 09:20 +07. Trạng thái {status}. Kỹ sư Hoàng Nam/điều phối Thu Hương. '
            body+=f'Nguyên nhân đã xác minh trong kịch bản: {cause}. Khắc phục: {fix}. Đóng lúc {stamp} 16:00 +07; khách xác nhận.' if closed else f'Giả thuyết: {cause}; chưa kết luận. Bước tiếp theo: lấy log đã che bí mật và đối chiếu cấu hình. Cập nhật cuối trong snapshot 05/09/2026 09:00: đang chờ log bổ sung từ khách; tham khảo {ref}.'
            rec('Ticket',tid,c['name']+' — '+issue,dict(customer_id=c['id'],status=status,severity='P2' if j==0 else 'P3',area=area,opened=stamp,engineer='Hoàng Nam',resolution=fix if closed else 'Đang xác minh'),body,TECH,customer=c['id'])
    # Anonymized lessons are available independent of customer ACL.
    lessons=[('VPN','VPN rớt định kỳ','Log cho thấy chu kỳ đàm phán lại trùng thời điểm mất kết nối; chưa đủ căn cứ để quy lỗi đường truyền.','Kiểm lifetime, proposal, route và thời gian hệ thống hai đầu; so sánh log cùng múi giờ.','Theo dõi ổn định sau change và lưu cấu hình trước/sau.'),('BACKUP','Backup chạy nhưng restore lỗi','Job thành công không chứng minh backup dùng được; cần restore test.','Kiểm chuỗi full/incremental, khóa mã hóa, quyền và dung lượng đích trong lab.','Lập lịch diễn tập và ghi bằng chứng đọc được dữ liệu.'),('WIFI','Roaming chậm','Người dùng mất phiên khi đi giữa hai AP; dữ liệu RF chưa đầy đủ.','Đo RSSI, kênh và mức nhiễu; kiểm SSID/VLAN và tương thích client.','Thử cùng tuyến đường và cùng thiết bị trước/sau.'),('WAF','False positive API','API upload hợp lệ bị chặn sau bật rule mới.','Thu request đã che dữ liệu, test staging, giới hạn ngoại lệ đúng endpoint.','Không tắt toàn bộ WAF vì một API bị chặn.'),('DNS','Ứng dụng không truy cập bằng tên','IP còn truy cập được nhưng DNS phân giải sai.','Kiểm resolver, TTL, zone nội bộ và split DNS; giữ bản cấu hình trước thay.','Thử nhiều client; phân biệt cache DNS và lỗi route.'),('STORAGE','Dung lượng tăng đột biến','Snapshot và retention có thể chiếm dung lượng chưa được tính.','Phân tích volume, lịch snapshot, thời hạn giữ và tốc độ tăng.','Không xóa snapshot/backup khi chưa có chính sách và người duyệt.')]
    for key,title,symptom,steps,lesson in lessons:
        doc('KB-'+key,title+' — bài học ẩn danh','Kinh nghiệm',f'Tình huống tổng hợp DEMO không gắn khách: {symptom} Kiểm tra: {steps} Bài học: {lesson} Nêu giả thuyết rõ, chỉ kết luận khi có log/test. Chuyển trưởng nhóm nếu ảnh hưởng nhiều site.',TECH)
    faqs=[('Tư vấn doanh nghiệp 100 người','Không chọn thiết bị chỉ theo 100 user. Gói firewall chuẩn có giá công 12 triệu, 4 ngày công; bổ sung lưu lượng, session, VPN và HA để sizing. Tham khảo RATE-FIREWALL.'),('Khách chưa có thiết bị có triển khai được không','Có thể bắt đầu khảo sát/thiết kế; chờ thiết bị và license trước cutover. Lịch gói chuẩn không gồm thời gian mua. Kiểm kho SKU và lead time mẫu.'),('Báo giá có gồm VAT không','Tất cả giá catalog DEMO chưa VAT, phần cứng và license nếu không có dòng riêng. Không tự áp dụng một thuế suất thật cho mọi hàng hóa.'),('Hai kỹ sư có làm nhanh gấp đôi không','Không luôn đúng vì khảo sát, test và bàn giao có phụ thuộc. Tổng ngày công không phải ngày lịch; PM kiểm đường găng.'),('Có hỗ trợ ngoài giờ không','PLUS/PREMIUM tiếp nhận 24x7; BASIC theo giờ phục vụ. Công ngoài scope phải phê duyệt theo BIZ-TRAVEL; đọc hợp đồng cụ thể.'),('Dịch vụ nào phù hợp công ty nhiều chi nhánh','Khảo sát đường truyền, ứng dụng tập trung và quyền truy cập; kết hợp firewall/VPN, Wi-Fi, giám sát và backup tùy nhu cầu. Báo effort theo mỗi site rồi PM sắp lịch.'),('Bàn giao xong có được đào tạo không','Gói triển khai có hướng dẫn vận hành theo scope. Khóa chuyên sâu riêng training: 5 triệu/2 buổi tối đa 10 học viên, 2 ngày công DEMO.'),('Có thể cam kết không downtime không','Chỉ cam kết theo thiết kế và test được duyệt. Migration có cửa sổ thay đổi và rollback; HA không đồng nghĩa không có rủi ro.'),('Nhắc gia hạn trước bao lâu','Theo BIZ-LICENSE, tạo nhắc trước 60/30/7 ngày; kiểm tài sản và license đúng SKU. Bản demo hiện có dữ liệu mẫu, không gửi nhắc thật.'),('Cần gì để mở ticket','Tên khách/site, tài sản, triệu chứng, thời điểm, ảnh hưởng, thay đổi gần nhất và log đã che bí mật; không yêu cầu mật khẩu. Điều phối phân loại mức độ.'),('Khác nhau giữa phản hồi và khôi phục','Phản hồi là tiếp nhận và bắt đầu phối hợp. Khôi phục là dịch vụ hoạt động lại. SLA P1 30 phút của PREMIUM là phản hồi, không phải sửa xong.'),('Có bán license Cloudflare không','Danh mục demo có tư vấn bảo vệ web/WAF. Giá và SKU Cloudflare thật chưa nhập; có thể soạn bảng yêu cầu ứng dụng/domain để lấy báo giá hãng, không tự bịa giá.')]
    for i,(q,a) in enumerate(faqs):doc(f'FAQ-SALE-{i+1:02}',q,'FAQ',a)
    # Retire obsolete fixture claims by replacing only known synthetic fixture versions at migration.
    byid={d['id']:d for d in docs}
    for cid,name,industry,sites,users,pkg in names[:2]:
        d=byid['CASE-'+cid];d.update(body=f'Hồ sơ khách giả lập {name}, mã {cid}; {sites} site; {users} user; gói {pkg}. Dữ liệu hiện hành ở CRM-{cid}, CONTRACT-{cid}, PROJECT-{cid}-01 và QUOTE-{cid}-01. Đây là khách tổng hợp, không phải khách thật.',version='company-demo-2.0',synthetic=True,as_of=SNAPSHOT)
    byid['POL-SLA'].update(body='Bảng gói bảo trì DEMO đã chuẩn hóa: BASIC 3.000.000 VND/tháng, 8x5, P1 4 giờ phục vụ, health-check mỗi quý; PLUS 6.500.000 VND/tháng, 24x7, P1 1 giờ, health-check hằng tháng; PREMIUM 12.000.000 VND/tháng, 24x7, P1 30 phút, health-check 2 lần/tháng. Giá cho 1 site/tối đa 10 thiết bị, chưa VAT. Đây là SLA phản hồi, không phải thời gian khôi phục. Xem SLA-BASIC, SLA-PLUS, SLA-PREMIUM và hợp đồng từng khách.',version='company-demo-2.0',synthetic=True)
    return dict(snapshot=SNAPSHOT,documents=list(byid.values()),services=services,packages=packages,clients=clients,records=records)

def install():
    data=ROOT/'data';data.mkdir(exist_ok=True);pack=build()
    # This function is only invoked explicitly for installing/updating the synthetic pack.
    with sqlite3.connect(data/'demo.sqlite3') as db:
        db.execute('CREATE TABLE IF NOT EXISTS docs(id TEXT PRIMARY KEY,payload TEXT NOT NULL)')
        added=updated=0
        for d in pack['documents']:
            row=db.execute('SELECT payload FROM docs WHERE id=?',(d['id'],)).fetchone()
            if row:
                old=json.loads(row[0])
                if old.get('version') not in ('demo-1.0','company-demo-2.0'):continue
                # Preserve explicit administrative retirement/approval state on already migrated records.
                if old.get('version')=='company-demo-2.0':d['status']=old['status']
                db.execute('UPDATE docs SET payload=? WHERE id=?',(json.dumps(d,ensure_ascii=False),d['id']));updated+=1
            else:db.execute('INSERT INTO docs VALUES(?,?)',(d['id'],json.dumps(d,ensure_ascii=False)));added+=1
    (data/'demo_documents.json').write_text(json.dumps(pack['documents'],ensure_ascii=False,indent=2),encoding='utf8')
    (data/'service_catalog.json').write_text(json.dumps(pack['services'],ensure_ascii=False,indent=2),encoding='utf8')
    (data/'company_operations.json').write_text(json.dumps({k:v for k,v in pack.items() if k not in ('documents','services')},ensure_ascii=False,indent=2),encoding='utf8')
    export=data/'company_documents';export.mkdir(exist_ok=True)
    for d in pack['documents']:
        (export/(d['id']+'.md')).write_text(f'# {d["title"]}\n\n> DỮ LIỆU GIẢ LẬP. Snapshot {SNAPSHOT}. Không phải chính sách thật.\n\nMã: {d["id"]} | Phiên bản: {d["version"]} | Vai trò: {", ".join(d["roles"])} | Khách: {d.get("customer") or "Chung"}\n\n'+d['body'],encoding='utf8')
    counts=dict(Counter(d['category'] for d in pack['documents']))
    report=dict(snapshot=SNAPSHOT,documents=len(pack['documents']),services=len(pack['services']),records=len(pack['records']),categories=counts,added=added,updated=updated)
    (data/'company_manifest.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8')
    print(json.dumps(report,ensure_ascii=True,indent=2))
if __name__=='__main__':install()
