from pathlib import Path
import re
p=Path('static/index.html');s=p.read_text(encoding='utf8')
s=s.replace('<span class="demo-tag">DEMO</span>','').replace('Local hoặc OpenRouter API','OpenRouter API').replace('CYBERANT / INTERNAL WORKSPACE / DEMO 01','CYBERANT / KNOWLEDGE WORKSPACE')
s=s.replace('Mật khẩu khởi tạo nằm trong file local <code>data/initial-accounts.json</code>.','Liên hệ quản trị để được cấp tài khoản hoặc đặt lại mật khẩu.')
s=s.replace('<label>Mật khẩu (để trống: tự tạo / giữ khi sửa)', '<label>Model được phép sử dụng<select id="user-model" required></select></label><label>Hạn mức token mỗi tháng (đầu vào + đầu ra, 0 = khóa gọi AI)<input id="user-token-limit" type="number" min="0" max="10000000000" value="1000000" step="1" required></label><label>Mật khẩu (để trống: tự tạo / giữ khi sửa)')
s=s.replace('<div id="users-table"></div>', '''<div id="users-table"></div><h2>Theo dõi token theo tháng</h2><p>Tháng tính theo UTC. Token đang giữ và lượt chưa rõ usage cũng được trừ khỏi hạn mức khả dụng. Xóa hội thoại không xóa lượng đã dùng.</p><div class="history-tools"><label>Tháng<input id="usage-month" type="month"></label><label>Tài khoản<select id="usage-user"><option value="">Tất cả tài khoản</option></select></label><button id="refresh-usage" class="secondary">Xem thống kê</button></div><div id="usage-summary"></div><div id="usage-records"></div><button id="usage-more" class="secondary hidden">Xem thêm lượt gọi</button><form id="reconcile-form" class="card hidden"><h3>Đối soát lượt chưa có usage</h3><p>Nhập số token đã xác minh từ OpenRouter. Không nhập 0 nếu chưa xác nhận lượt gọi không tính token.</p><input id="reconcile-id" type="hidden"><label>Token đầu vào<input id="reconcile-prompt" type="number" min="0" max="1000000000" required></label><label>Token đầu ra<input id="reconcile-completion" type="number" min="0" max="1000000000" required></label><label>Bằng chứng / ghi chú<input id="reconcile-note" minlength="10" maxlength="1000" required></label><button class="primary">Ghi nhận đối soát</button></form>''')
start=s.index('<section id="view-system"');end=s.index('<section id="view-admin"',start)
s=s[:start]+'''<section id="view-system" class="view hidden"><div class="page-heading"><div><h1>Hệ thống OpenRouter</h1><p id="metrics-time"></p></div><button id="refresh-health" class="secondary">Làm mới</button></div><div id="system-info" class="system-grid"></div><div id="provider-summary" class="card"></div><div class="card"><h2>Dữ liệu và vận hành</h2><div id="system-counts"></div><button id="sync-knowledge" class="secondary">Đồng bộ kho tri thức</button><button id="system-backup" class="secondary">Sao lưu cơ sở dữ liệu</button></div></section>
''' +s[end:]
s=s.replace('<p id="account-description"></p>','<p id="account-description"></p><p id="account-usage"></p>')
p.write_text(s,encoding='utf8')
p=Path('static/app.js');s=p.read_text(encoding='utf8')
start=s.index('async function checkHealth()');end=s.index('const suggestions=',start)
s=s[:start]+'''async function checkHealth(){try{if(!currentUser){await api('/health');$('#model-pill').textContent='OpenRouter';return}health=await api('/model');$('#model-pill').classList.toggle('off',!health.configured);$('#model-pill').textContent=health.model+' · OpenRouter';await refreshAccountUsage()}catch{$('#model-pill').textContent='Mất kết nối hoặc hết phiên'}}
async function refreshAccountUsage(){if(!currentUser)return;const u=await api('/account/usage');$('#account-usage').textContent=`Tháng ${u.month} (UTC): ${u.used_tokens.toLocaleString('vi-VN')} / ${u.monthly_token_limit.toLocaleString('vi-VN')} token · Còn ${u.remaining_tokens.toLocaleString('vi-VN')} · Model ${u.model}`;}
''' +s[end:]
s=s.replace("runtimeFormDirty=false;checkHealth();",'checkHealth();')
s=s.replace("if(view==='system'){checkHealth();loadSystem(true).catch(e=>toast(e.message))}","if(view==='system'){checkHealth();loadSystem().catch(e=>toast(e.message))}if(view==='account')refreshAccountUsage().catch(e=>toast(e.message));")
s=s.replace("renderSources(data.sources,data.citations_verified)","renderSources(data.sources,data.citations_verified);refreshAccountUsage().catch(()=>{})")
p.write_text(s,encoding='utf8')
