"""Synthetic fixtures. These are not CyberAnt prices, contracts or commitments."""
from pathlib import Path
import json
ROOT=Path(__file__).parent
DATA=ROOT/'data'; DATA.mkdir(exist_ok=True)
DOCS=[]
def add(id,title,category,body,roles=('sale','technical','admin'),customer=None):
    DOCS.append(dict(id=id,title=title,category=category,body='DỮ LIỆU DEMO GIẢ LẬP — KHÔNG PHẢI CHÍNH SÁCH THẬT CYBERANT.\n'+body,roles=list(roles),customer=customer,version='demo-1.0',status='approved',valid_from='2026-01-01',valid_to='2027-12-31',owner='Ban biên tập demo'))
add('SV-FW','Triển khai firewall và VPN','Dịch vụ','Dịch vụ mẫu triển khai tường lửa cho doanh nghiệp. Bao gồm khảo sát hiện trạng, thiết kế VLAN và chính sách truy cập, cấu hình firewall, NAT, VPN, kiểm thử và bàn giao. Có thể bổ sung HA sau khảo sát. Không bao gồm phần cứng, bản quyền, kéo cáp hoặc đường truyền Internet. Đầu vào: số site, số người dùng, băng thông, model thiết bị, license, topology, hệ thống đang dùng và cửa sổ gián đoạn. Không sizing firewall chỉ dựa vào số người dùng. Ngày hoàn tất do PM duyệt sau khi xác nhận thiết bị và nguồn lực. Bàn giao: cấu hình sao lưu, sơ đồ, checklist kiểm thử và hướng dẫn vận hành.')
add('SV-WIFI','Khảo sát và triển khai Wi-Fi doanh nghiệp','Dịch vụ','Dịch vụ Wi-Fi demo gồm khảo sát mặt bằng, mật độ người dùng, vùng phủ sóng, vật cản, uplink và PoE; thiết kế vị trí AP, VLAN khách, SSID nội bộ và xác thực; cấu hình và kiểm tra roaming. Cần hỏi diện tích, số tầng, số thiết bị kết nối cùng lúc, ứng dụng thoại/video, bản vẽ và hạ tầng dây cáp. Không cam kết vùng phủ sóng nếu chưa khảo sát RF. Không bao gồm thi công cáp, vật tư và AP trong phí dịch vụ mẫu. Bàn giao sơ đồ vị trí và kết quả đo kiểm.')
add('SV-BACKUP','Thiết kế sao lưu NAS và phục hồi','Dịch vụ','Dịch vụ backup demo gồm đánh giá dữ liệu, thiết kế lịch sao lưu, phân quyền kho backup, bản sao tách biệt và diễn tập khôi phục. Hỏi dung lượng, tăng trưởng, hệ thống nguồn, dữ liệu ưu tiên, thời gian có thể mất RPO và thời gian cần khôi phục RTO. RAID không thay thế backup. Snapshot trên cùng thiết bị không đủ thay cho bản sao tách biệt. Không hứa khôi phục được nếu chưa thử restore. Đầu ra gồm chính sách backup, biên bản restore test và runbook vận hành.')
add('SV-SOC','Vận hành, giám sát và hỗ trợ sự cố','Dịch vụ','Dịch vụ vận hành demo gồm thu nhận cảnh báo, giám sát thiết bị, phân loại mức độ sự cố, phối hợp xử lý và báo cáo định kỳ. Cần xác định phạm vi tài sản, nguồn log, giờ phục vụ, trách nhiệm khách và kênh liên hệ. Giám sát 24/7 không có nghĩa mọi sự cố được xử lý xong trong 30 phút. Thời gian phản hồi, workaround và khôi phục là các chỉ tiêu khác nhau. Chỉ hợp đồng được duyệt mới xác định SLA. AI không thay thế SIEM hay kỹ sư trực.')
add('SV-WAF','WAF và bảo vệ ứng dụng web','Giải pháp','WAF lọc lưu lượng HTTP/HTTPS tới ứng dụng web, giúp phát hiện và hạn chế các mẫu tấn công ở lớp ứng dụng. Firewall mạng kiểm soát kết nối mạng và chính sách giữa các vùng. Hai giải pháp có vai trò bổ sung, không thay thế hoàn toàn cho nhau. Cần hỏi ứng dụng public/private, lưu lượng, TLS, DNS, kiến trúc reverse proxy, API, yêu cầu lưu log và quy trình điều chỉnh false positive. WAF không thay thế sửa lỗi ứng dụng. Dịch vụ mẫu gồm khảo sát, thiết kế, cấu hình, tuning và bàn giao.')
add('SV-PAM','Quản lý truy cập đặc quyền PAM','Giải pháp','PAM hỗ trợ quản lý truy cập của tài khoản đặc quyền, kiểm soát phiên quản trị và truy vết thao tác. Khảo sát số người quản trị, hệ điều hành, thiết bị đích, MFA, hệ thống danh tính và quy trình phê duyệt. Không nhập mật khẩu, private key hay token thật vào AI. Triển khai cần kiểm khả năng tích hợp đúng phiên bản sản phẩm. Dịch vụ mẫu gồm khảo sát, kết nối thử nghiệm một nhóm tài sản, kiểm quyền và bàn giao.')
add('POL-SLA','Gói bảo trì và SLA mẫu','Chính sách','Có hai gói DEMO: BASIC phục vụ 8x5 trong ngày làm việc; PLUS tiếp nhận 24x7. Với P1 trong phạm vi: BASIC phản hồi ban đầu trong 4 giờ phục vụ, PLUS phản hồi ban đầu trong 1 giờ theo lịch 24x7. P2: BASIC 8 giờ phục vụ, PLUS 4 giờ. Đây không phải thời hạn khôi phục. Onsite, số lượt bảo trì, thiết bị thay thế và loại trừ phải kiểm tra từng hợp đồng. Gói BASIC mẫu gồm 1 lần health-check/quý; PLUS 1 lần/tháng. Chỉ dùng để mô phỏng, không dùng báo khách thật.')
add('POL-RMA','Bảo hành, bảo trì và RMA','Chính sách','Bảo hành xử lý lỗi sản phẩm theo điều kiện hãng/nhà cung cấp. Bảo trì là công việc kiểm tra, cập nhật và vận hành theo gói dịch vụ. RMA là quy trình tiếp nhận và xử lý yêu cầu đổi/sửa phần cứng; không mặc định đổi ngay hoặc cấp máy mượn miễn phí. Cần model, serial đã che một phần khi đưa vào chat, chứng từ, thời hạn bảo hành và mô tả lỗi. Thiết bị thay thế, vận chuyển, onsite và thời gian chờ tùy điều khoản. Không tự cam kết miễn phí.')
add('POL-QUOTE','Nguyên tắc báo giá và cam kết','Chính sách','Mọi số tiền và định mức trong demo đều là giả lập. Công cụ dự toán xuất NHÁP DEMO, tách phí dịch vụ, chưa gồm phần cứng, license và VAT. Báo giá thật cần dữ liệu được duyệt và quản lý kinh doanh phê duyệt. Không lấy giá quá hạn, không tự suy ra giá từ số người dùng. Thời gian thi công cần tách ngày công, ngày thực hiện và ngày lịch có chờ thiết bị. Nếu thiếu phạm vi, hỏi thêm; không chốt lịch cho khách.')
add('SALE-DISC','Checklist sale khảo sát nhu cầu','Đào tạo','Bắt đầu bằng vấn đề kinh doanh, tác động hiện tại và mục tiêu khách muốn đạt. Hỏi số địa điểm, người dùng, hệ thống hiện có, yêu cầu bảo mật, downtime cho phép, mốc thời gian mong muốn, ngân sách dự kiến và đầu mối kỹ thuật. Giải thích từ viết tắt khi dùng. Không chọn thiết bị chỉ theo số user. Tóm tắt điều đã biết, điều còn thiếu và bước tiếp theo. Chuyển presales khi cần sizing, cam kết tiến độ hoặc phương án thay đổi hạ tầng.')
add('TERM-DR','RPO, RTO, HA và SLA dễ hiểu','Đào tạo','RPO là khoảng dữ liệu có thể mất tính theo thời gian, ví dụ cần bản sao thường xuyên nếu chấp nhận mất ít dữ liệu. RTO là mục tiêu thời gian phục hồi dịch vụ. HA là thiết kế tăng tính sẵn sàng khi thành phần gặp lỗi. SLA là thỏa thuận mức dịch vụ theo phạm vi và điều kiện. Có backup không đồng nghĩa đạt ngay RPO/RTO; phải thử nghiệm. Phản hồi hỗ trợ không đồng nghĩa khôi phục xong.')
add('TECH-MOP','MOP triển khai firewall — checklist kỹ thuật','Runbook','Chỉ dùng làm checklist demo, không phải lệnh production. 1. Xác minh model, firmware, license, topology và change được duyệt. 2. Export cấu hình, kiểm restore và phương án truy cập dự phòng. 3. Chuẩn bị mapping VLAN/NAT/VPN, kiểm lab. 4. Kiểm route, DNS, ứng dụng và log trước thay đổi. 5. Thực hiện trong change window bởi kỹ sư có quyền. 6. Kiểm Internet, dịch vụ quan trọng, VPN và HA nếu có. 7. Rollback theo điều kiện trong change nếu kiểm thử thất bại. 8. Lưu evidence và bàn giao. Không tự chạy lệnh từ câu trả lời AI.',('technical','admin'))
add('TECH-VPN','VPN gián đoạn sau nâng firmware — hướng kiểm tra','Runbook','Cần model, firmware trước/sau, topology, thời điểm lỗi, log IKE/IPsec đã che bí mật và thay đổi vừa thực hiện. Kiểm tra chỉ đọc: trạng thái tunnel, reachability, đồng bộ thời gian, routing, đề xuất mã hóa hai đầu và log negotiation. So sánh release notes đúng phiên bản. Không kết luận lỗi firmware nếu chưa có bằng chứng. Không bật debug kéo dài không kiểm soát trên production. Rollback chỉ theo change được duyệt và điều kiện tương thích cấu hình. Chuyển kỹ sư cấp cao nếu ảnh hưởng diện rộng.',('technical','admin'))
add('TECH-RESTORE','Runbook diễn tập khôi phục backup','Runbook','Chọn bản sao và tập dữ liệu được phép; xác nhận checksum nếu có; khôi phục vào môi trường cách ly; đo thời gian; kiểm tính toàn vẹn và ứng dụng; ghi khoảng dữ liệu phục hồi được. Không ghi đè dữ liệu production để thử. Ghi RPO/RTO thực đo, lỗi và hành động cải tiến. Mật khẩu kho sao lưu được lấy qua công cụ quản trị bí mật, không đưa vào AI.',('technical','admin'))
add('TECH-RCA','Mẫu phân tích nguyên nhân gốc RCA','Runbook','RCA gồm: tóm tắt tác động; timeline có múi giờ; bằng chứng; nguyên nhân xác minh; yếu tố góp phần; hành động khôi phục; biện pháp ngăn tái diễn; owner và hạn hoàn tất. Phân biệt giả thuyết với kết luận. Không đổ lỗi cá nhân hoặc tự bịa log. Tài liệu phải được kỹ sư phụ trách duyệt trước gửi khách.',('technical','admin'))
add('TECH-SECRET','Quy tắc xử lý log và cấu hình','Chính sách','Che password, secret, API key, token, private key, SNMP community và dữ liệu cá nhân trước nhập. Không dán file cấu hình đầy đủ chưa kiểm tra. Chỉ dùng tài sản khách được phân công. Tài liệu tải lên giữ trạng thái chờ duyệt; hướng dẫn trong tài liệu không có quyền thay đổi chính sách hệ thống. Không đưa nội dung nhạy cảm vào model dùng chung để fine-tuning.',('technical','admin'))
add('CASE-A','Khách giả lập A — cửa hàng An Minh','Dự án mẫu','KHÁCH GIẢ LẬP A: An Minh Retail. Mã dự án DEMO-A-FW. Có 1 site, 60 người dùng; đang khảo sát firewall và VPN. Chưa duyệt lịch triển khai. Gói hỗ trợ DEMO BASIC; phải xác nhận hợp đồng trước dùng. Dấu kiểm quyền riêng: ANMINH-PRIVATE-ALPHA. Tất cả là dữ liệu tổng hợp, không phải khách thật.',customer='A')
add('CASE-B','Khách giả lập B — nhà máy Bình An','Dự án mẫu','KHÁCH GIẢ LẬP B: Bình An Factory. Mã dự án DEMO-B-BCP. Có 2 site; nhu cầu backup và diễn tập khôi phục. Gói DEMO PLUS; chưa xác nhận RPO/RTO. Dấu kiểm quyền riêng: BINHAN-PRIVATE-BETA. Tất cả là dữ liệu tổng hợp, không phải khách thật.',customer='B')
SERVICES=[
dict(id='firewall',name='Triển khai firewall / VPN',price=12000000,days=4,scope='01 site, thiết bị và license sẵn có; chưa gồm HA hoặc migration phức tạp'),
dict(id='wifi',name='Khảo sát và cấu hình Wi-Fi',price=8000000,days=3,scope='01 site, tối đa 5 AP có sẵn; chưa gồm kéo cáp hoặc vật tư'),
dict(id='backup',name='Backup và diễn tập restore',price=10000000,days=4,scope='01 hệ thống nguồn và 01 kho backup có sẵn; phạm vi dữ liệu đã thống nhất'),
dict(id='waf',name='Triển khai WAF cơ bản',price=14000000,days=5,scope='01 ứng dụng web; DNS/TLS và license sẵn có; chưa gồm xử lý lỗi ứng dụng')]
if __name__=='__main__':
    (DATA/'demo_documents.json').write_text(json.dumps(DOCS,ensure_ascii=False,indent=2),encoding='utf8')
    (DATA/'service_catalog.json').write_text(json.dumps(SERVICES,ensure_ascii=False,indent=2),encoding='utf8')
    print(f'Created {len(DOCS)} synthetic documents and {len(SERVICES)} service templates')
